apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-movieapp-deployment
  namespace: movie-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-movieapp
  template:
    metadata:
      labels:
        app: my-movieapp
    spec:
      containers:
      - name: my-movieapp-container
        image: "202516164812.dkr.ecr.us-east-1.amazonaws.com/gorsh"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: my-movieapp-service
  namespace: movie-app
spec:
  type: LoadBalancer
  selector:
    app: my-movieapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80